Homework2: Andrei Kadushko
Shurke/pt1-43-21 pull request #10
Opened 2021-10-28 15:00 UTC by AndreiKadushko

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-10-30 17:30 UTC, AndreiKadushko commented
All tasks!

2021-10-31 18:34 UTC, Shurke requested changes
Общие замечание.
1. Имена переменных. Стоит давать осознанные и осмысленные имена, чтобы они несли смысл.
2. Между строкой документации модуля и основным кодом, согласно РЕР8 вставляются пробельные строки.

2021-10-31 18:34 UTC, Shurke commented on src/Homework2/task2.py
> +my_string = input('Введите предложение: ')
Строка документации, импорт и основной код по РЕР8 разделяются пробельными строками.

2021-10-31 18:34 UTC, Shurke commented on src/Homework2/task2.py
> +        word = i
Как вариант, можно сделать так:
```python
max_len_word = max(my_string_wo.split(), key=len)
```
И тогда не нужно итерироваться еще раз.

2021-10-31 18:34 UTC, Shurke commented on src/Homework2/task3.py
> +    my_string_out = my_string_out + i
В таких случаях логичнее писать условие, которое удовлетворяет нас:
```py
if i not in my_string_out and i != ' ':
    my_string_out += i
```

2021-10-31 18:34 UTC, Shurke commented on src/Homework2/task8_2.py
> +    def get_digit(dgt):
Из-за отсутствия строк документации, а также пояснений в приглашении к вводу и выводу данных, сложно понять решение и правильное ли оно.

2021-10-31 18:34 UTC, Shurke commented on src/Homework2/task8_3.py
> +def printer_error(s):
См. замечание к `src/Homework2/task8_2.py`.

2021-11-06 12:24 UTC, Shurke requested changes
С пятой задачи именование переменных идет не по РЕР8. 
Текущая оценка - 7.5. Предлагаю доработать и повысить оценку.

2021-11-06 12:24 UTC, Shurke commented on src/Homework2/task4.py
> +my_string = input('Введите строку: ')
Строка документации модуля должна быть отделена от кода пробельными строками по РЕР8.

2021-11-06 12:24 UTC, Shurke commented on src/Homework2/task5.py
> +Fib = int(input('Введите номер числа Фибоначчи: '))
Строка документации модуля должна быть отделена от кода пробельными строками по РЕР8.

2021-11-06 12:24 UTC, Shurke commented on src/Homework2/task6.py
> +A = int(input('Введите число: '))
Строка документации модуля должна быть отделена от кода пробельными строками по РЕР8.

2021-11-06 12:24 UTC, Shurke commented on src/Homework2/task7.py
> +tri_str = input('Введите три стороны треугольника (через запятые):').split(',')
Строка документации модуля должна быть отделена от кода пробельными строками по РЕР8.

2021-11-06 17:54 UTC, AndreiKadushko commented
Сорри, были проблемы по отправке Homework4, не успел поправить

2021-11-07 13:51 UTC, Shurke reviewed
Итоговая отметка - 8.5.

2021-11-07 13:51 UTC, Shurke commented on src/Homework2/task5.py
> +    print(number_fib, '-ое число Фибоначчи: 0', sep='')
С первым как все нормально "первое число Фибоначчи", а вот с третьим уже будут проблемы.)

2021-11-07 13:57 UTC, closed without merging