PR - Homework1: Nastassia Khodar
Shurke/pt1-43-21 pull request #11
Opened 2021-10-30 12:02 UTC by khodar-nastassia

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-10-31 18:49 UTC, Shurke requested changes
Общие замечания:
1. Имена переменных. Стоит давать осознанные и осмысленные имена, чтобы они несли смысл.
2. На будущее, условия задач оформлять как строки документации модуля.
3. 8я задача предусматривает решение 5 задач. У вас только 3.

2021-10-31 18:49 UTC, Shurke commented on src/homework2/task2.py
> +import re
Импорт от строки документации также должен отделяться пробельной строкой.

2021-10-31 18:49 UTC, Shurke commented on src/homework2/task2.py
> +                max_word = word
Если вы придумали, как поделить строку на слова через регулярку, то тогда стоит посмотреть в сторону встроенной функции `max()` и сделать свое решение максимально изящным.)

2021-10-31 18:49 UTC, Shurke commented on src/homework2/task3.py
> +    result = "".join(dict.fromkeys(strWithoutSpace))
С версии [Python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation), словарь действительно является упорядоченным. Но это не фича, а всего лишь побочный, пусть и приятный эффект, который мы имеем от решения другой проблемы.
Поэтому, лучше решать задачу более явно, с использованием типа данных, который гарантирует упорядоченность.
Хотя, справедливости ради, стоит отметить, что с версии 3.7 это уже гарантируется.)

2021-10-31 18:49 UTC, Shurke commented on src/homework2/task4.py
> +import re
В данной задаче можно и через модуль `string` решать.

2021-10-31 18:49 UTC, Shurke commented on src/homework2/task5.py
> +    main()
В решении имеется ошибка.
5-е число Фибоначчи - это 3. Ваш алгоритм говорит, что это 5, которое является 6-м.
Числа Фибоначчи: 0, 1, 1, 2, 3, 5.

2021-10-31 18:49 UTC, Shurke commented on src/homework2/task8-1.py
> +    return input()
В чем смысл создания функции для ввода данных?
Если можно вместо вызова данной функции просто вызвать функцию `input()`.

2021-11-01 16:19 UTC, khodar-nastassia commented on src/homework2/task2.py
> +import re
исправлено

2021-11-01 16:36 UTC, khodar-nastassia commented on src/homework2/task2.py
> +                max_word = word
Посмотрела функцию мах(). с числами разобралась как делать, а со строками-нет.

2021-11-01 16:37 UTC, khodar-nastassia commented on src/homework2/task3.py
> +    result = "".join(dict.fromkeys(strWithoutSpace))
спасибо. буду знать о приятном эффекте)))

2021-11-01 16:44 UTC, khodar-nastassia commented on src/homework2/task4.py
> +import re
хммм, я попыталась через модуль string сделать, но у модуля не оказалось функции match():
![image](https://user-images.githubusercontent.com/81435332/139708153-f3ae0f31-a32f-4ed3-8912-021a2fb9818e.png)

2021-11-01 16:52 UTC, khodar-nastassia commented on src/homework2/task5.py
> +    main()
Исправлено

2021-11-01 17:01 UTC, khodar-nastassia commented on src/homework2/task8-1.py
> +    return input()
согласна. это было лишнее))

2021-11-06 12:54 UTC, Shurke reviewed
Итоговая оценка 9.

2021-11-06 12:54 UTC, Shurke commented on .vscode/launch.json
> +{
Файлы, которые не относятся к IDE не должны попадать в домашнюю работу.

2021-11-06 12:54 UTC, Shurke commented on src/homework2/task2.py
> +                max_word = word
```python
words = re.split(r'(s\+|,s\+)|(s\+|!|\.|\?)', string)
max_word = max(words, key=len)
```

2021-11-06 12:54 UTC, Shurke commented on src/homework2/task4.py
> +import re
В модуле `string` имеются константы:
1. `ascii_uppercase` содержит `ABCDEFGHIJKLMNOPQRSTUVWXYZ `
2. `ascii_lowercase` содержит `abcdefghijklmnopqrstuvwxyz `

2021-11-06 12:54 UTC, Shurke commented on src/homework2/task4.py
> +    countSmallLetter = 0
Переменные должны именоваться по snake_case.

2021-11-07 13:58 UTC, closed without merging