PR - Homework4: Nastassia Khodar
Shurke/pt1-43-21 pull request #13
Opened 2021-10-31 08:34 UTC by khodar-nastassia

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-07 09:14 UTC, Shurke requested changes

2021-11-07 09:14 UTC, Shurke commented on .gitignore
> +.vscode
Сам файл `.gitignore` тоже стоит поместить в `.gitignore`.)

2021-11-07 09:14 UTC, Shurke commented on src/homework4/task3.py
> +    tuple1 = (4, )
> при итерировании по этому элементу последовательно выводились значения 1, 2, 3.

Вы в своем решении создаете генератор и только после получается значения.

2021-11-07 09:14 UTC, Shurke commented on src/homework4/task4.py
> +    numbers = [int(s) for s in input().split()]
Стоит добавлять приглашения ко вводу, а также пояснения к тому, что вы печатаете на экран в конце работы программы.

2021-11-07 09:14 UTC, Shurke commented on src/homework4/task5.py
> +                break
Мне кажется, что использование метода списка `count` облегчит задачу.

2021-11-07 09:14 UTC, Shurke commented on src/homework4/task6.py
> +    main()
Осечка вышла.)
<img width="731" alt="Screenshot 2021-11-07 at 11 14 01" src="https://user-images.githubusercontent.com/44495358/140637500-cf189779-8405-43a4-b4bb-4aad448c5e04.png">

2021-11-08 17:41 UTC, khodar-nastassia commented on .gitignore
> +.vscode
он добавлен, вот:
![image](https://user-images.githubusercontent.com/81435332/140791255-18e6aa22-b532-4ae7-b8c5-72fc8ab71cfa.png) 
Или я что-то не так сделала?

2021-11-08 17:57 UTC, khodar-nastassia commented on src/homework4/task3.py
> +    tuple1 = (4, )
исправлено

2021-11-08 18:11 UTC, khodar-nastassia commented on src/homework4/task4.py
> +    numbers = [int(s) for s in input().split()]
дополнены приглашение ко вводу и  пояснения к выводимому на экран значению

2021-11-08 18:41 UTC, khodar-nastassia commented on src/homework4/task5.py
> +                break
Спасибо. решение так просто, когда знаешь что когда и как использовать.

2021-11-08 19:17 UTC, khodar-nastassia commented on src/homework4/task6.py
> +    main()
Исправлено. Похоже работает:
![image](https://user-images.githubusercontent.com/81435332/140803808-1c9946c2-8d8e-4c1d-8d57-071b5e501e60.png)

2021-11-15 17:47 UTC, Shurke requested changes

2021-11-15 17:47 UTC, Shurke commented on src/homework4/task2.py
> +    numberLetters.pop(1)
Напомню, что по PEP8 предпочтительным является использование `snake_case`. 
Таким образом
```py
pair_of_letters
number_letters
```

2021-11-15 17:47 UTC, Shurke commented on src/homework4/task6.py
> +    main()
Нит.
Не работает.)
![Screenshot 2021-11-15 at 20 45 56](https://user-images.githubusercontent.com/44495358/141829526-79ca29d9-a0ee-46e0-bb3c-9ca4698883f0.png)

Осечка спряталась в 10 строке. ;)

2021-11-17 07:13 UTC, khodar-nastassia commented on src/homework4/task2.py
> +    numberLetters.pop(1)
Да, спасибо, вы мне уже писали об этом. В тот момент мое внимание было направлено на правильность решения задач, а не на правильность оформления. Как результат -  в памяти не отложилось. Сейчас точно запомню. Спасибо

2021-11-23 06:42 UTC, khodar-nastassia commented on src/homework4/task6.py
> +    main()
Моя ошибка вызвана разность ввода цифр. я вводила через пробел, и  тогда нужен сплит. Если вводить без пробела, то и сплит не нужен. и тогда все будет работать.
![два](https://user-images.githubusercontent.com/81435332/142980724-72a63e6e-3286-4fb2-8123-14314f0f8ce6.png)

2021-11-28 18:26 UTC, Shurke reviewed
Итоговая отметка - 8.

2021-11-28 18:27 UTC, closed without merging