Homework_4
Shurke/pt1-43-21 pull request #16
Opened 2021-10-31 19:16 UTC by MrGo1d

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-07 09:22 UTC, Shurke requested changes

2021-11-07 09:22 UTC, Shurke commented on src/Homework_4/task4.py
> +list_of_num = input()
Если вы хотите, чтобы пользователь что-то ввел, то нужно писать приглашение ко вводу.

2021-11-07 09:22 UTC, Shurke commented on src/Homework_4/task2.py
> +# step#1
Сначала должен быть комментарий, а потом строка к которой дан комментарий.

2021-11-08 18:30 UTC, MrGo1d commented on src/Homework_4/task4.py
> +list_of_num = input()
Исправил: написал приглашение к вводу

2021-11-08 18:30 UTC, MrGo1d commented on src/Homework_4/task2.py
> +# step#1
Исправил.

2021-11-15 17:50 UTC, Shurke reviewed
Итоговая оценка - 8.5.

2021-11-15 17:50 UTC, closed without merging