Homework3: Ales Rovba (смотрим папку homework3)
Shurke/pt1-43-21 pull request #19
Opened 2021-11-01 14:39 UTC by Ranok3

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-07 09:36 UTC, Shurke requested changes

2021-11-07 09:36 UTC, Shurke commented on src/homework3/task1.py
> +        b.append('FizzBuzz')
`print('FizzBuzz')`

2021-11-07 09:36 UTC, Shurke commented on src/homework3/task1.py
> +        b.append('Fizz')
`print('Fizz')`

2021-11-07 09:36 UTC, Shurke commented on src/homework3/task1.py
> +        b.append('Buzz')
print('Buzz')

2021-11-07 09:36 UTC, Shurke commented on src/homework3/task4.py
> +c = 0
Неочевидные имена для счетчиков.
Если о значении `с` еще можно догадаться, то для чего нужен счетчик `i` - нет.

2021-11-07 09:36 UTC, Shurke commented on src/homework3/task5.py
> +            list2.append(item1)
Применение метода `count` упрощает решение.

2021-11-07 09:36 UTC, Shurke commented on src/homework3/task6.py
> +        print('n = ', n)
Данные инструкции являются отладочными. И их не должно быть в финальном решении.

2021-11-07 09:36 UTC, Shurke commented on src/homework3/task1.py
> +for i in a:
```python
b = []
for i in range(1, 101):
```
Можно использовать такое вариант. Функция `range` создаст генератор и будет отдавать значения по одному, не помещая в память весь список от 1 до 100.

2021-11-07 12:49 UTC, Ranok3 commented on src/homework3/task1.py
> +        b.append('Fizz')
Поменял

2021-11-07 12:49 UTC, Ranok3 commented on src/homework3/task1.py
> +        b.append('Buzz')
Поменял

2021-11-07 12:50 UTC, Ranok3 commented on src/homework3/task1.py
> +        b.append('FizzBuzz')
Поменял

2021-11-07 12:53 UTC, Ranok3 commented on src/homework3/task4.py
> +c = 0
как я должен назвать i по правильному?

2021-11-07 12:54 UTC, Ranok3 commented on src/homework3/task5.py
> +            list2.append(item1)
Может и так, люблю делать нестандартно)

2021-11-07 12:54 UTC, Ranok3 commented on src/homework3/task6.py
> +        print('n = ', n)
Согласен, удалил

2021-11-07 12:57 UTC, Ranok3 commented on src/homework3/task1.py
> +for i in a:
понял, поменял

2021-11-15 17:54 UTC, Shurke reviewed
Итоговая оценка - 8.5.

2021-11-15 17:54 UTC, Shurke commented on src/homework3/task4.py
> +c = 0
Так, чтобы было понятно, что там хранится. К примеру, для переменной `с` это может быть `pairs_counter`.

2021-11-15 17:55 UTC, closed without merging