Homework2: Miron Chuduk
Shurke/pt1-43-21 pull request #2
Opened 2021-10-23 19:50 UTC by MironChuduk

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-10-29 14:18 UTC, Shurke requested changes
Файлы `.DS_Store` и `src/.DS_Store` не должны присутствовать в домашнем задании. 

Общие замечания:
1. Имена переменных. Стоит давать осознанные и осмысленные имена, чтобы они несли смысл.
2. На будущее, условия задач оформлять как строки документации модуля.

2021-10-29 14:18 UTC, Shurke commented on src/homework2/task2.py
> +import string
По РЕР8 импорт отделяется от кода пробельными строками.

2021-10-29 14:18 UTC, Shurke commented on src/homework2/task5.py
> +    print("Ошибка ввода!")
Не верное решение. 
5-е число Фибоначчи - это 3. Ваш алгоритм говорит, что это 5, которое является 6-м.
Числа Фибоначчи: 0, 1, 1, 2, 3, 5 ...

2021-10-29 14:18 UTC, Shurke commented on src/homework2/task7.py
> +            print("Не существует!")
Необходимое условие существования треугольника можно поместить в одну проверку, тем самым уменьшив количество повторяющегося кода.

2021-11-06 10:14 UTC, Shurke requested changes
Файлы `.DS_Store` и `src/.DS_Store` должны быть добавлены в `.gitignore`.

Есть некоторые замечания. Предлагаю исправить и повысить оценку. 
Без исправлений - оценка 7.5.

2021-11-06 10:14 UTC, Shurke commented on src/homework2/task2.py
> +        result = i
Не самое оптимальное решение задачи. Можно обойтись всего одним проходом коллекции.

2021-11-06 10:14 UTC, Shurke commented on src/homework2/task4.py
> +my_string = input()
Пропущены пробельные строки, согласно РЕР8.

2021-11-06 10:14 UTC, Shurke commented on src/homework2/task8.4.py
> +new_string = new_string.strip("-")
Данную задачу можно решить только с использованием методов строки.

2021-11-08 11:44 UTC, MironChuduk commented on src/homework2/task8.4.py
> +new_string = new_string.strip("-")
Исправлено

2021-11-08 11:44 UTC, MironChuduk commented on src/homework2/task4.py
> +my_string = input()
Исправлено

2021-11-08 11:44 UTC, MironChuduk commented on src/homework2/task2.py
> +        result = i
Исправлено

2021-11-11 19:50 UTC, Shurke reviewed
Лишних файлов, не относящихся к домашней работе стало больше.
Итоговая оценка - 8.

2021-11-11 19:51 UTC, closed without merging