Homework5: Ales Rovba
Shurke/pt1-43-21 pull request #29
Opened 2021-11-03 20:36 UTC by Ranok3

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 18:30 UTC, Shurke requested changes
1. Именование переменных не исправлено. Оставлено на уровне отдельных букв и цифр, либо изменение ключевых слов языка с помощью `_`.
2. Ко всем инструкциям `input()` с клавиатуры стоит добавить приглашение ко вводу.
3. При выводе ответа задания на экран также необходимо добавить пояснение тому, что вы водите на экран.

2021-11-15 18:30 UTC, Shurke commented on src/homework5/task1.py
> +print(d)
Если вывод всего словаря на экран мне понятен, то для чего нужно выводить `d[2]` остается загадкой.

2021-11-15 18:30 UTC, Shurke commented on src/homework5/task2.py
> +n = int(input())
Если вы хотите получить ввод от пользователя, то стоит добавлять приглашения ко вводу, чтобы было понятно, что ожидается от пользователя.

2021-11-15 18:30 UTC, Shurke commented on src/homework5/task5.py
> +    print(s)
Для чего тут помещен вывод на экран?

2021-11-15 18:30 UTC, Shurke commented on src/homework5/task5.py
> +print(len(s1), '\n', s1)
Стоит добавить пояснение, что выведено на экран.

2021-11-15 18:30 UTC, Shurke commented on src/homework5/task7.py
> +m = int(input())
Тоже замечание о приглашении ко вводу, что и выше.

2021-11-15 18:53 UTC, Ranok3 commented on src/homework5/task1.py
> +print(d)
Поправил

2021-11-15 18:54 UTC, Ranok3 commented on src/homework5/task2.py
> +n = int(input())
Первый раз такое слышу, помню на занятиях писали просто

2021-11-15 18:55 UTC, Ranok3 commented on src/homework5/task5.py
> +    print(s)
Поправил

2021-11-15 18:56 UTC, Ranok3 commented on src/homework5/task5.py
> +print(len(s1), '\n', s1)
На занятиях мы пишем без пояснения, делаю так как на занятиях

2021-11-15 18:56 UTC, Ranok3 commented on src/homework5/task7.py
> +m = int(input())
Такой же ответ что и выше

2021-11-15 19:00 UTC, Ranok3 commented
Общее 
п1. Дайте мне названия переменных, которые я могу использовать. Не помню такого списка
п2 и п3. Делаю так как на занятиях

2021-11-28 18:29 UTC, Shurke commented on src/homework5/task2.py
> +# Смотрел в гугле, как я должен был догадаться до такого просто из головы, понятия не имею
На сколько сильно оказало влияние гугла на ваше решение?

2021-11-28 19:32 UTC, Ranok3 commented on src/homework5/task2.py
> +# Смотрел в гугле, как я должен был догадаться до такого просто из головы, понятия не имею
Без гугла не решил бы

2021-12-13 17:56 UTC, Shurke commented
Итоговая оценка - 8.

2021-12-13 17:57 UTC, closed without merging