Homework2: Andrei Barysevich
Shurke/pt1-43-21 pull request #3
Opened 2021-10-24 20:33 UTC by Crankymonk

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-10-29 14:12 UTC, Shurke requested changes
Общие замечания:
1. Имена переменных. Стоит давать осознанные и осмысленные имена, чтобы они несли смысл.
2. На будущее, условия задач оформлять как строки документации модуля.

2021-10-29 14:12 UTC, Shurke commented on src/homework1/homework1.py
> +m = input('Enter the cost, rubles - ')
Задача намного легче, чем представленное решение.
Стоит подумать над тем, как стоит упростить.

2021-10-29 14:12 UTC, Shurke commented on src/homework2/task1.py
> +# 1. Напишите программу, которая считает общую цену.
Дубликат предыдущего файла.

2021-10-29 14:12 UTC, Shurke commented on src/homework2/task2.py
> +# print(st1)
Если строка закомментирована, значит она не должна быть в конечном решении.

2021-10-29 14:12 UTC, Shurke commented on src/homework2/task4.py
> +# 97 - 122 - small in ASCII
`isupper()` и `islower()` решают данную задачу более явным образом.

2021-10-29 14:12 UTC, Shurke commented on src/homework2/task6.py
> +# print(lista)
См. замечание про закомментированный код.

2021-10-29 14:12 UTC, Shurke commented on src/homework2/task7.py
> +lst.append(c)
Для чего необходимо добавление в список?

2021-10-29 14:12 UTC, Shurke commented on src/homework2/task7.py
> +    s = ((p * ((p - a) * (p - b) * (p - c))) ** 0.5)  # Формула Герона для площади треугольника
Не вижу перевода из строкового представления в числовой вид.

2021-10-29 14:12 UTC, Shurke commented on src/homework2/task8.1.py
> +    print(a)
Для чего нужен данный `print`?

2021-10-30 22:37 UTC, Crankymonk commented on src/homework1/homework1.py
> +m = input('Enter the cost, rubles - ')
Решение простое, просто добавил пару проверок, чтобы избежать некорректного ввода)

2021-10-30 22:44 UTC, Crankymonk commented on src/homework2/task8.1.py
> +    print(a)
Проверял, тот ли элемент отлавливается после цикла.
удаляю

2021-10-30 23:02 UTC, Crankymonk commented on src/homework2/task4.py
> +# 97 - 122 - small in ASCII
Еще можно поставить проверку на интервалах без использования ord()  (
for i in entered_symbols:
    if ('A' <= i <= 'Z'):
        uppercase_words += 1
    elif ('a' <= i <= 'z'):
        lowercased_words += 1)

2021-10-30 23:19 UTC, Crankymonk commented on src/homework2/task7.py
> +    s = ((p * ((p - a) * (p - b) * (p - c))) ** 0.5)  # Формула Герона для площади треугольника
Добавил на входе данных перевод

2021-10-31 12:25 UTC, Crankymonk commented on src/homework2/task7.py
> +lst.append(c)
На тот момент - единственный известный мне способ отсортировать по возрастанию, чтобы исполнить проверку на существование треугольника
Сейчас знаю еще один вариант покороче `sorted([a, b, c])`

2021-11-06 10:31 UTC, Shurke requested changes
В 5 и 6  задаче не соблюдено условие.
Предлагаю исправить и повысить оценку. 
На данный момент - оценка 8.

2021-11-06 10:31 UTC, Shurke commented on src/homework2/task5.py
> +fib_element = fib_sequence[1]
Хочу обратить внимание на условие:

> только временные переменные, циклические операторы и условные операторы.

Пожалуйста, соблюдайте условие задачи.

2021-11-06 10:31 UTC, Shurke commented on src/homework2/task6.py
> +list_b = []
Снова обращаю внимание на уловие.

> Число положительное целое, произвольной длины. Задача требует работать только с числами (без конвертации числа в строку или что-нибудь еще).

2021-11-06 10:31 UTC, Shurke commented on src/homework1/homework1.py
> +
Данный файл дублируется.

2021-11-06 15:18 UTC, Crankymonk commented on src/homework2/task5.py
> +fib_element = fib_sequence[1]
Переделал, спасибо

2021-11-06 15:18 UTC, Crankymonk commented on src/homework2/task6.py
> +list_b = []
Переделал

2021-11-06 15:18 UTC, Crankymonk commented on src/homework1/homework1.py
> +
удалил

2021-11-07 14:27 UTC, Shurke reviewed
Итоговая оценка - 8.5.

2021-11-07 14:27 UTC, Shurke commented on src/homework2/task5.py
> +print(str(number_in_fib) + 'th Fibonacci number is - ' + str(fib_element))
`first`, `second` и `third` выдают из данного подхода.

2021-11-07 14:28 UTC, closed without merging