Homework4: Miron Chuduk
Shurke/pt1-43-21 pull request #31
Opened 2021-11-03 21:15 UTC by MironChuduk

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-07 09:55 UTC, Shurke requested changes
`src/.DS_Store` и `src/homework4/.DS_Store` должны быть убраны.

2021-11-07 09:55 UTC, Shurke commented on src/homework4/task1.py
> +for i in range(100):
`range(1, 101)` и не будет необходимости везде дописывать `+1`.

2021-11-07 09:55 UTC, Shurke commented on src/homework4/task4.py
> +print(counter)
Стоит добавить пояснение, что выводится на экран.

2021-11-07 09:55 UTC, Shurke commented on src/homework4/task5.py
> +    element = i
Для чего создавать промежуточную переменную?

2021-11-07 09:55 UTC, Shurke commented on src/homework4/task6.py
> +i = 0
Для чего нужна данная переменная?
Не вижу необходимости в ней, т.к. далее в коде не используется.

2021-11-08 11:44 UTC, MironChuduk commented on src/homework4/task1.py
> +for i in range(100):
Исправлено

2021-11-08 11:44 UTC, MironChuduk commented on src/homework4/task4.py
> +print(counter)
Исправлено

2021-11-08 11:45 UTC, MironChuduk commented on src/homework4/task5.py
> +    element = i
Исправлено

2021-11-08 11:45 UTC, MironChuduk commented on src/homework4/task6.py
> +i = 0
Исправлено

2021-11-15 18:03 UTC, Shurke reviewed
Итоговая оценка - 8.

2021-11-15 18:03 UTC, Shurke commented on src/homework4/task6.py
> +print(li)
Можно было бы здесь сформировать красивую строку для вывода на экран и добавить пояснение, как в предыдущих задачах.

2021-11-15 18:03 UTC, closed without merging