homework4 + change directory of homework2
Shurke/pt1-43-21 pull request #37
Opened 2021-11-04 15:27 UTC by KirPython

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-07 10:11 UTC, Shurke requested changes
Обратите внимание на именование переменных. Очень много имен в виде одной буквы. Имя переменной должно нести смысл о том, что в ней находится.

2021-11-07 10:11 UTC, Shurke commented on src/homework2/task1.py
> +    price = float(input("Введите цену товара: "))
По условию задачи вводятся отдельно количество рублей, потом количество копеек. 
У вас никак не учитывается это условие.

2021-11-07 10:11 UTC, Shurke commented on src/homework2/task2.py
> +    Учтите что в предложении есть знаки препинания.
Не учтено.

2021-11-07 10:11 UTC, Shurke commented on src/homework2/task3.py
> +    str_ = list(str_)
Нет смысла в том, чтобы из строки формировать список и потом формировать из списка строку.

2021-11-07 10:11 UTC, Shurke commented on src/homework2/task4.py
> +        if string.ascii_letters.find(letter) != -1:
```py
if letter in string.ascii_letters:
```
будет более правильным решением.

2021-11-07 10:11 UTC, Shurke commented on src/homework4/task1.py
> +            print("FizzBuzz", end=' ')
Для чего изменять окончание строки?

2021-11-07 10:11 UTC, Shurke commented on src/homework4/task5.py
> +        if s == 1:
Это можно делать в рамках одной строки.

2021-11-07 10:11 UTC, Shurke commented on src/homework4/task5.py
> +    a = [int(i) for i in input().split()]
Если хотите, чтобы пользователь что-то ввел, то стоит писать приглашение ко вводу для понимания того, что нужно сделать.

2021-11-15 18:19 UTC, Shurke requested changes
Обратите внимание на именование переменных и поработаете с этим. Использовать ключевые слова языка и добавлять к ним `_` является не самой лучшей тактикой.

2021-11-15 18:19 UTC, Shurke commented on src/homework2/task2.py
> +    str1 = input("Введите любое предложение: ")
Импорт осуществляется на уровне модуля, а не в функции.

2021-11-15 18:19 UTC, Shurke commented on src/homework2/task4.py
> +    str_ = list(str_)
У вас переменная хранит сначала строку, потом список. Но при этом имя переменной никак не отображает того, что она несет в себе.
В идеале должно было быть что-то вроде
```py
input_str = input("Введите любую строку: ")
processed_str = input_str.replace(' ', '')
list_of_letters = list(processed_str)
```

2021-11-15 18:19 UTC, Shurke commented on src/homework4/task5.py
> +            lst2.append(element)
Для чего нужен второй список?
В коде он никак не используется далее.

2021-11-15 18:19 UTC, Shurke commented on src/homework2/task3.py
> +    print(new_st)
Стоит добавить пояснение, что вы выводите на экран.

2021-11-15 18:19 UTC, Shurke commented on src/homework2/task5.py
> +    print(cur)
Смотрите выше про пояснения.

2021-11-15 18:19 UTC, Shurke commented on src/homework4/task3.py
> +    print(len(tuple1))
Смотрите выше про пояснения.

2021-11-15 18:19 UTC, Shurke commented on src/homework4/task6.py
> +    print(lst)
Смотрите выше про пояснения.

2021-11-28 18:32 UTC, Shurke reviewed
Обе домашки засчитаны с оценкой 7.

2021-11-28 18:32 UTC, Shurke commented on src/homework4/task5.py
> +            lst2.append(element)
Вопрос остался актуальным.

2021-11-28 18:33 UTC, closed without merging

2021-11-30 18:33 UTC, KirPython commented on src/homework4/task5.py
> +            lst2.append(element)
В списке могут быть элементы, которые повторяются несколько раз. Чтобы не проверять их также по несколько раз, вводится второй список в качестве хранилища уникальных значений первого списка. Второй список используется в цикле для проверки того, что мы ранее не обрабатывали уже элемент списка с аналогичным значением.