Homework5: Elena Okun
Shurke/pt1-43-21 pull request #38
Opened 2021-11-06 11:54 UTC by ElenaOkun

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 18:42 UTC, Shurke requested changes

2021-11-15 18:42 UTC, Shurke commented on src/homework5/task2.py
> +        list_of_cities.append(input("Введите город: "))
Скорее придирка. Тут стоило писать во множественном числе.

2021-11-15 18:42 UTC, Shurke commented on src/homework5/task3.py
> +print(len(set1 & set2))
А где пояснение тому, что вы выводите на экран?)

2021-11-15 18:42 UTC, Shurke commented on src/homework5/task4.py
> +print(len(set1 ^ set2))
См. замечание выше.

2021-11-15 18:42 UTC, Shurke commented on src/homework5/task5.py
> +    print(len(known_by_somebody), *known_by_somebody, sep="\n")
См. замечание про пояснения.

2021-11-15 18:42 UTC, Shurke commented on src/homework5/task7.py
> +print(number1) if number1 != 0 else print(number2)
См. замечание про пояснения.

2021-11-15 18:42 UTC, Shurke commented on src/homework5/task2.py
> +def find_country():
Стоит организовать решение таким образом, что исходный словарь передается в функцию как аргумент, а не через глобальную переменную.

2021-11-15 18:42 UTC, Shurke commented on src/homework5/task2.py
> +    dict1 = dict()
`dict_city_country` это более явное имя для данного словаря.

2021-11-16 18:18 UTC, ElenaOkun commented on src/homework5/task3.py
> +print(len(set1 & set2))
Исправлено

2021-11-16 19:29 UTC, ElenaOkun commented on src/homework5/task5.py
> +    print(len(known_by_somebody), *known_by_somebody, sep="\n")
Добавила описание к выводу результата

2021-11-16 19:30 UTC, ElenaOkun commented on src/homework5/task7.py
> +print(number1) if number1 != 0 else print(number2)
Добавила описание к выводу результата

2021-11-16 19:41 UTC, ElenaOkun commented on src/homework5/task2.py
> +def find_country():
Исправила

2021-11-16 19:41 UTC, ElenaOkun commented on src/homework5/task2.py
> +    dict1 = dict()
Исправила

2021-11-16 19:42 UTC, ElenaOkun commented on src/homework5/task2.py
> +        list_of_cities.append(input("Введите город: "))
Исправила

2021-11-16 20:02 UTC, ElenaOkun commented on src/homework5/task4.py
> +print(len(set1 ^ set2))
Добавила описание к выводу результата

2021-11-21 18:56 UTC, Shurke reviewed
Итоговая оценка - 8.5

2021-11-21 18:56 UTC, closed without merging