Homework5: Nastassia Khodar
Shurke/pt1-43-21 pull request #39
Opened 2021-11-06 12:27 UTC by khodar-nastassia

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 18:50 UTC, Shurke requested changes
В домашней работе имеются файлы, которые относятся к предыдущим дз.

2021-11-15 18:50 UTC, Shurke commented on src/homework5/task1.py
> +    dct = {int(element1 + 1): (element1 + 1) ** 3 for element1 in range(20)}
`range(1, 21)` и не надо ничего добавлять.)

2021-11-15 18:50 UTC, Shurke commented on src/homework5/task2.py
> +    listOfCities = []
`snake_case` [PEP8](https://www.python.org/dev/peps/pep-0008/#toc-entry-32)

2021-11-15 18:50 UTC, Shurke commented on src/homework5/task2.py
> +    for _ in range(int(input('Ведите число: '))):
`input('Ведите число городов для проверки: ')` было бы более понятно.)

2021-11-15 18:50 UTC, Shurke commented on src/homework5/task3.py
> +    print(len(set(firstList) | set(secondList)))
Стоит все же добавить пояснение тому, что выводится на экран.

2021-11-15 18:50 UTC, Shurke commented on src/homework5/task7.py
> +    b = 462
Ну как бы можно было и через `input()` получить.)

2021-11-15 18:50 UTC, Shurke commented on src/homework5/task5.py
> +                for _ in range(int(input('Введите количество школьников : ')))]
Изящно, но не слишком читаемо.

2021-11-15 18:50 UTC, Shurke commented on src/homework5/task4.py
> +    print(len(set(firstList) ^ set(secondList)))
Стоит все же добавить пояснение тому, что выводится на экран.

2021-11-23 07:27 UTC, khodar-nastassia commented on src/homework5/task1.py
> +    dct = {int(element1 + 1): (element1 + 1) ** 3 for element1 in range(20)}
Ну да, так проще.  Исправлено. Спасибо

2021-11-23 07:37 UTC, khodar-nastassia commented on src/homework5/task2.py
> +    listOfCities = []
Прошу прощения. эта домашку делала до закрепления в памяти snake_case. Исправлено

2021-11-23 07:38 UTC, khodar-nastassia commented on src/homework5/task2.py
> +    for _ in range(int(input('Ведите число: '))):
Добавлены пояснения на ввод и вывод

2021-11-23 07:44 UTC, khodar-nastassia commented on src/homework5/task3.py
> +    print(len(set(firstList) | set(secondList)))
Добавлены пояснения на ввод и вывод

2021-11-23 07:52 UTC, khodar-nastassia commented on src/homework5/task4.py
> +    print(len(set(firstList) ^ set(secondList)))
Добавлены пояснения на ввод и вывод. Названия переменных по snake_case

2021-11-23 08:03 UTC, khodar-nastassia commented on src/homework5/task7.py
> +    b = 462
Исправлено

2021-11-23 11:57 UTC, khodar-nastassia commented on src/homework5/task5.py
> +                for _ in range(int(input('Введите количество школьников : ')))]
переписала.

2021-11-28 18:25 UTC, Shurke reviewed
Итоговая отметка - 8.

2021-11-28 18:25 UTC, closed without merging