Homework2: Ales Rovba
Shurke/pt1-43-21 pull request #4
Opened 2021-10-24 22:10 UTC by Ranok3

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-10-29 14:04 UTC, Shurke requested changes
Общие замечания:
1. Имена переменных. Стоит давать осознанные и осмысленные имена, чтобы они несли смысл.
2. На будущее, условия задач оформлять как строки документации модуля.

2021-10-29 14:04 UTC, Shurke commented on src/homework2/main.py
> +# This is a sample Python script.
Данный файл никак не относится к домашней работе. И следует его удалить.

2021-10-29 14:04 UTC, Shurke commented on src/homework2/task2.py
> +import string
Согласно РЕР8, импорт стоит отделять от остального кода пробельными строками.

2021-10-29 14:04 UTC, Shurke commented on src/homework2/task2.py
> +        print(i__)
Не думаю, что есть необходимость в двойном обходе одной и той же коллекции.
Стоит подумать над тем, как избежать этого.

2021-10-29 14:04 UTC, Shurke commented on src/homework2/task8-3.py
> +        b = b + 1
Для чего нужен счетчик `b`? Если он нигде не используется.

2021-10-29 14:04 UTC, Shurke commented on src/homework2/task5.py
> +print("Значение этого элемента:", fib2)
Скопированное решение из гугла не верно.
5-е число Фибоначчи - это 3. Ваш алгоритм говорит, что это 5, которое является 6-м.
Числа Фибоначчи: 0, 1, 1, 2, 3, 5 ...

2021-10-29 17:55 UTC, Ranok3 commented on src/homework2/main.py
> +# This is a sample Python script.
удалил

2021-10-29 17:56 UTC, Ranok3 commented on src/homework2/task2.py
> +import string
Отделил

2021-10-29 18:22 UTC, Ranok3 commented on src/homework2/task2.py
> +        print(i__)
Поменял, не могу проверить, перестали запускаться программы

2021-11-06 10:39 UTC, Shurke requested changes
1. Замечание о именовании переменных проигнорировано.
2. В задаче имеются задачи из следующей домашней задачи. Чего быть не должно. 

Предлагаю доработать домашнюю работу и улучшить оценку.
Оценка на данный момент - 7.

2021-11-06 10:39 UTC, Shurke commented on src/homework2/task6.py
> +c = 0
Переменная `с` нигде не используется.

2021-11-06 10:39 UTC, Shurke commented on src/homework2/task8-3.py
> +        b = b + 1
Вопрос остается актуальным.

2021-11-06 12:25 UTC, Ranok3 commented
тест

2021-11-06 12:29 UTC, Ranok3 reviewed
m1

2021-11-06 12:29 UTC, Ranok3 commented on src/homework2/task8-3.py
> +        b = b + 1
Чтобы посчитать только те 0, которые в начале строки

2021-11-06 12:29 UTC, Ranok3 commented on src/homework2/task5.py
> +print("Значение этого элемента:", fib2)
перед решением было что-то вроде: есть очень много дебатов, надо ли учитывать 0 в начале. Наше решение для варианта без 0 в начале

2021-11-06 12:29 UTC, Ranok3 commented on src/homework2/task5.py
> +print("Значение этого элемента:", fib2)
Поправил

2021-11-07 14:13 UTC, Shurke reviewed
Итоговая отметка - 8.

2021-11-07 14:13 UTC, Shurke commented on src/homework2/task8-3.py
> +        b = b + 1
Исходя из 16-й строки, то 0 в начале строки считает счетчик `n`.
Кроме того, счетчик `b` будет увеличиваться всегда с момента, когда вначале строки будет найден первый не нулевой элемент
![Screenshot 2021-11-07 at 17 06 03](https://user-images.githubusercontent.com/44495358/140648358-0fcaebe6-5e10-4fa1-8e7c-30496d7048bb.png)
.

2021-11-07 14:13 UTC, closed without merging