Homework5: Andrei Barysevich
Shurke/pt1-43-21 pull request #40
Opened 2021-11-07 14:20 UTC by Crankymonk

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 18:53 UTC, Shurke requested changes

2021-11-15 18:53 UTC, Shurke commented on src/homework5/task2.py
> +N = int(input('Введите количество стран: '))
`number_of_countries` как имя переменной выглядит куда лучше.

2021-11-15 18:53 UTC, Shurke commented on src/homework5/task2.py
> +M = int(input('Кол-во запросов: '))
См. предыдущие замечание.

2021-11-15 18:53 UTC, Shurke commented on src/homework5/task3.py
> +print(len(set_difference))
Стоит все же добавлять пояснение тому, что выводится на экран.

2021-11-15 18:53 UTC, Shurke commented on src/homework5/task4.py
> +print(len(set_1_diff))
Стоит все же добавлять пояснение тому, что выводится на экран.

2021-11-15 18:53 UTC, Shurke commented on src/homework5/task5.py
> +N = int(input('Введите количество школьников: '))
См. замечание в задаче 2.

2021-11-15 18:53 UTC, Shurke commented on src/homework5/task5.py
> +print('\n'.join(language_pool))  # Выводим все известные языки с новой строки
Стоит все же добавлять пояснение тому, что выводится на экран.

2021-11-15 18:53 UTC, Shurke commented on src/homework5/task6.py
> +print(len(set_words))
Стоит все же добавлять пояснение тому, что выводится на экран.

2021-11-15 18:53 UTC, Shurke commented on src/homework5/task7.py
> +print(great_comm_divisor)
Стоит все же добавлять пояснение тому, что выводится на экран.

2021-11-16 18:09 UTC, Crankymonk commented on src/homework5/task2.py
> +N = int(input('Введите количество стран: '))
Я думал, что нужно как в задаче все переменные задавать...

2021-11-16 18:54 UTC, Crankymonk commented on src/homework5/task7.py
> +print(great_comm_divisor)
Думаю, после этой домашки я надолго запомню это правило)

2021-11-21 19:00 UTC, Shurke reviewed
Итоговая оценка - 8.5.

2021-11-21 19:00 UTC, closed without merging