Homework5: Andrei Kadushko
Shurke/pt1-43-21 pull request #41
Opened 2021-11-08 16:16 UTC by AndreiKadushko

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 19:07 UTC, Shurke requested changes

2021-11-15 19:07 UTC, Shurke commented on src/Homework5/task2.py
> +number_country = int(input())
Если вы ожидаете от пользователя получить данные через клавиатуру, то стоит добавить приглашения к вводу данных.

2021-11-15 19:07 UTC, Shurke commented on src/Homework5/task3.py
> +                    split()))
Не надо все пытаться впихнуть в одну строку. Вы за них не платите и нет смысла экономить.)
```py
input_data = input('Введите первый список чисел через пробел: ')
set_number_1 = set(map(int, input_data.split()))
```
выглядит куда более читаемо.

2021-11-15 19:07 UTC, Shurke commented on src/Homework5/task4.py
> +set_number_1 = (set(int(x) for x in
Смотрите замечание выше.

2021-11-15 19:07 UTC, Shurke commented on src/Homework5/task5.py
> +[print(i) for i in all_language]
Для чего `print()` помещается в список?

2021-11-15 19:07 UTC, Shurke commented on src/Homework5/task2.py
> +[print(*country) for country in country_list]
Для чего `print()` помещается в список?

2021-11-15 19:07 UTC, Shurke commented on src/Homework5/task6.py
> +[my_set.add(i) for i in input('Введите строку: ').split()]
Вам не кажется, что это слишком сложно?
```py
input_data = input('Введите строку: ')
my_set = set(input_data.split())
```

2021-11-20 17:18 UTC, AndreiKadushko commented on src/Homework5/task3.py
> +                    split()))
Я думал, это круто :(

2021-11-28 18:23 UTC, Shurke reviewed
Итоговая отметка - 8.

2021-11-28 18:23 UTC, Shurke commented on src/Homework5/task5.py
> +# [print(i) for i in least_one_language]
Думаю, что здесь этого не должно быть.

2021-11-28 18:23 UTC, closed without merging