Homework5: Alexander Ustinov
Shurke/pt1-43-21 pull request #42
Opened 2021-11-08 16:42 UTC by MrGo1d

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 19:14 UTC, Shurke requested changes

2021-11-15 19:14 UTC, Shurke commented on src/Homework_5/task2.py
> +# в итоге O(N)*O(N)*O(N) = O(N^3)
А теперь стоит подумать над тем, можно ли что-то сделать, чтобы уменьшить сложность решения.)

2021-11-15 19:14 UTC, Shurke commented on src/Homework_5/task6.py
> +# O(N^3)
А теперь стоит подумать над тем, можно ли что-то сделать, чтобы уменьшить сложность решения.)

2021-11-18 19:36 UTC, MrGo1d commented on src/Homework_5/task2.py
> +# в итоге O(N)*O(N)*O(N) = O(N^3)
Немного оптимизировал код и добавил констркуцию 'break'.

2021-11-18 19:37 UTC, MrGo1d commented on src/Homework_5/task6.py
> +# O(N^3)
Удалось обойтись одним перебором и однойой проверкой на вхождение.

2021-11-22 15:29 UTC, Shurke requested changes

2021-11-22 15:29 UTC, Shurke commented on src/Homework_5/task2.py
> +def task2(tup_of_req, dict_of_cities):
А как же условие, что вводить с клавиатуры?)

2021-11-22 15:29 UTC, Shurke commented on src/Homework_5/task6.py
> +        if (not char.isalpha()) and char != ' ':
В скобки `not char.isalpha()` брать не обязательно.

2021-11-22 15:29 UTC, Shurke commented on src/Homework_5/task6.py
> +    for char in str_:
Если написать `input_str`, то нет необходимости менять ключевое слово языка.

2021-11-22 15:29 UTC, Shurke commented on src/Homework_5/task7.py
> +print(NOD)
Я думаю, что 
```py
print(f"Наибольший общий делитель ровняется {NOD}")
```
выглядит куда понятнее.)

2021-11-27 17:51 UTC, MrGo1d commented on src/Homework_5/task2.py
> +def task2(tup_of_req, dict_of_cities):
Упс...Откорректировал!

2021-11-27 17:51 UTC, MrGo1d commented on src/Homework_5/task6.py
> +        if (not char.isalpha()) and char != ' ':
Убрал скобки

2021-11-27 17:52 UTC, MrGo1d commented on src/Homework_5/task6.py
> +    for char in str_:
Дельный совет: откорректировал!)

2021-11-27 17:52 UTC, MrGo1d commented on src/Homework_5/task7.py
> +print(NOD)
Готово.

2021-11-28 18:21 UTC, Shurke reviewed
Итоговая отметка - 9. 
+1 балл за оценку сложности.

2021-11-28 18:21 UTC, closed without merging