Homework5: Kirill Filitchonok
Shurke/pt1-43-21 pull request #43
Opened 2021-11-08 18:10 UTC by KirPython

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 19:18 UTC, Shurke requested changes

2021-11-15 19:18 UTC, Shurke commented on src/homework5/task2.py
> +        print(cname)
Я думаю, что в 20 и 29 строках инструкции `print()` использовались для отладки и в итоговом решении уже не нужны.

2021-11-15 19:18 UTC, Shurke commented on src/homework5/task3.py
> +    print(len(cross))
Стоит добавить пояснение тому, что выведено на экран.

2021-11-15 19:18 UTC, Shurke commented on src/homework5/task4.py
> +    print(len(diff))
Стоит добавить пояснение тому, что выведено на экран.

2021-11-15 19:18 UTC, Shurke commented on src/homework5/task6.py
> +    print(len(set_))
Стоит добавить пояснение тому, что выведено на экран.

2021-11-15 19:18 UTC, Shurke commented on src/homework5/task5.py
> +            print(item)
Вывод ответа должен находиться на уровне с 29 строкой, а не внутри блока if.

2021-11-28 18:19 UTC, Shurke reviewed
Итоговая отметка - 8.

2021-11-28 18:20 UTC, closed without merging

2021-11-30 18:33 UTC, KirPython commented on src/homework5/task5.py
> +            print(item)
Вывод ответа верный, т.к. если количество школьников не больше одного, то по условию задачи скрипт ничего не должен выводить