Homework5: Danila Kritsky
Shurke/pt1-43-21 pull request #46
Opened 2021-11-09 10:35 UTC by danilakritsky

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 19:31 UTC, Shurke requested changes
Как насчет того, чтобы начать писать unit test?)
Тем самым разгрузим решение задачи и вынесем тесты отдельно, т.е. `task1.py` и `test_task1.py`.
И вы потренируетесь что-то новое делать. К примеру, добавите тест в 6-ю задачу.

2021-11-21 16:57 UTC, danilakritsky commented
@Shurke Александр, я напишу вам позже, как договаривались. Пока очень отстаю по 7-ой домашке и материалам последних лекций - нужно разгрести, прежде чем браться за что-то еще.

2021-11-22 16:15 UTC, Shurke reviewed
Итоговая оценка - 10. 
Оставил ряд замечаний, это скорее больше передача опыта, чем замечание. 
Пул реквест закрывать не буду, если захотите - доработаете. Если нет, то закроете сами.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/task2.py
> +    )
Если уже углубляться дальше, то вашу большую функцию `main()` стоит разбить на более мелкие функции. 
Тем самым, не только просто осуществлять код ревью, но и потом поддерживать код. Когда имеются отдельный небольшие функциональные единицы, проще понимать что и как.
Также, при более мелком делении на функции, удобнее покрывать тестами. 
Выделенный участок стоит вынести в отдельную функцию, как подготовительный этап работы.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/task2.py
> +        locations_dict.update({city: country for city in cities})
Эта часть также может быть вынесена в отдельный метод.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/task2.py
> +        print(locations_dict.get(city_match[0], 'City not found.'))
Эта часть также может быть вынесена в отдельный метод.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/task5.py
> +def main() -> None:
Замечание к данной задаче аналогично замечаниям к задаче 2.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/test_task1.py
> +class TestMain(unittest.TestCase):
В книге Фредерика Брукса "Мифический человеко-месяц" описывается следующий подход при написании тестов:
- пишется тест на заведомо правильную работу тестируемой функции;
- пишется тест на заведомо неправильную работу тестируемой функции (в том числе все ошибочные и исключительные ситуации);
- пишутся тесты на все крайние случаи работы тестируемой функции.

Это скорее замечание на будущее.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/test_task3.py
> +    def test_output(self) -> None:
В тестах уже не обязательно использовать аннотирование, т.к. не несет здесь большой практической пользы. Кроме того, большинство тестов у вас без аннотации.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/test_task4.py
> +        ]
Для параметризации тестов используется модуль `ddt`.  И позволяет сделать тело теста более простым и читаемым.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/test_task6.py
> +        # pylint: disable=W0613
Есть такой лайфхак, когда нужно передать что-то в функцию, т.к. требуется (например, при патчинге теста), но не используется в коде:
```py
def test_no_input(self, _):
```
И тогда не будет нужды дизейблить pylint.

2021-11-22 16:15 UTC, Shurke commented on src/homework5/test_task6.py
> +        # pylint: disable=W0613
Есть еще такой вариант, когда опять же что-то нужно передать, но не используется в функции:
```py
def test_output(self, mock_stdout, mock_input):
        """Test the output of the main() function."""
        del mock_input
```
Таким образом можно удалить неограниченное количество переданных аргументов, которые не будут использоваться.

2021-11-28 18:32 UTC, danilakritsky commented
Исправил согласно комментариям.

2021-12-02 12:35 UTC, Shurke reviewed
11, к сожалению, поставить не могу.)

2021-12-02 12:35 UTC, closed without merging