Homework5: Miron Chuduk
Shurke/pt1-43-21 pull request #47
Opened 2021-11-09 12:10 UTC by MironChuduk

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-15 19:35 UTC, Shurke requested changes

2021-11-15 19:35 UTC, Shurke commented on src/homework5/task2.py
> +                break
А почему не использовать оператор `in` для проверки вхождения города в список городов?

2021-11-15 19:35 UTC, Shurke commented on src/homework5/task6.py
> +print(f"Всего слов: {len(my_list)}")
Не учтено условие про различные слова.

2021-11-16 15:39 UTC, MironChuduk commented on src/homework5/task2.py
> +                break
Исправлено

2021-11-16 15:39 UTC, MironChuduk commented on src/homework5/task6.py
> +print(f"Всего слов: {len(my_list)}")
Исправлено

2021-11-22 15:48 UTC, Shurke reviewed
Итоговая оценка - 8.

2021-11-22 15:48 UTC, closed without merging