Homework7: Nastassia Khodar
Shurke/pt1-43-21 pull request #49
Opened 2021-11-13 09:59 UTC by khodar-nastassia

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-23 06:22 UTC, khodar-nastassia commented
Здравствуйте. Не могу пройти тесты в первой задаче. Можете подсказать, как это сделать.  Первая ошибка, как я поняла, заключается в том ,что импорты модулей идут после указания пути. Но если не указывать путь - модули не видны. Вторая ошибка в блоке match--case. Эту конструкцию я сделала по образцу, найденному на просторах. что я сделала не так? Спасибо

2021-11-23 15:29 UTC, Shurke commented on src/homework7/task1.py
> +sys.path.append('src/homework7/utils/')
Данная строка должна идти после всех импортов.

2021-11-23 15:29 UTC, Shurke commented on src/homework7/task1.py
> +        case "task2_1":
Pattern matching появился в Python 3.10. 
Наш код запускается на 3.9, вот и ошибка.)

2021-11-24 18:40 UTC, khodar-nastassia commented on src/homework7/task1.py
> +sys.path.append('src/homework7/utils/')
Исправила. спасибо

2021-11-24 18:40 UTC, khodar-nastassia commented on src/homework7/task1.py
> +        case "task2_1":
буду знать на будущее

2021-12-02 12:44 UTC, Shurke reviewed
Как общее замечание, в функциях отсутствуют строки документации.

2021-12-02 12:44 UTC, Shurke commented on src/homework7/task1.py
> +def all_task():
Любое изменение в модуле `tasks` приведет к тому, что вам руками нужно будет исправлять код. При этом, есть достаточно легкий способ, как получить список имен всех функций автоматически. 
`dir(tasks)` и `getattr(tasks, "func_name")` помогут вам убрать все то количество `if`, что у вас имеется.

2021-12-02 12:44 UTC, Shurke commented on src/homework7/task2.py
> +    return wrapper
> (за все время вызовов, не только текущий запуск программы)

Данная часть условия не соблюдена.

2021-12-02 12:44 UTC, Shurke commented on src/homework7/task5.py
> +def collect_Ratings(rating):
Напоминаю про РЕР8 и правила именования функций.

2021-12-02 13:09 UTC, Shurke requested changes

2021-12-02 13:09 UTC, Shurke commented on src/homework7/task5.py
> +    readFile = open('src/homework7/ratings.list', 'r')
Для работы с файлом лучше использовать контекстный менеджер.

2021-12-02 13:09 UTC, Shurke commented on src/homework7/task5.py
> +    years_movies = open('src/homework7/out/years.txt', 'a')
Кроме того, что работу с файлами лучше осуществлять в контекстном менеджере, хочу еще обратить внимание вот на что. В данном случае, сначала стоит подготовить данные, а только потом открыть файл и осуществить запись. 
Т.к. пока файл открыт, вы аллоцировали ресурс. И с этим ресурсом может что-то случиться за время выполнения программы, т.к. ваш код не контролирует состояние файла. И в результате, данные могут быть потеряны.

2021-12-02 13:09 UTC, Shurke commented on src/homework7/task5.py
> +    write_Years(years_movies)
Я бы рекомендовал не передавать файл внутрь функции, а прямо в самой функции открывать и осуществлять запись.

2021-12-11 13:40 UTC, khodar-nastassia commented on src/homework7/task1.py
> +def all_task():
исправлено

2021-12-11 13:40 UTC, khodar-nastassia commented on src/homework7/task2.py
> +    return wrapper
исправлено

2021-12-11 13:41 UTC, khodar-nastassia commented on src/homework7/task5.py
> +def collect_Ratings(rating):
нет мне прощения

2021-12-11 13:41 UTC, khodar-nastassia commented on src/homework7/task5.py
> +    readFile = open('src/homework7/ratings.list', 'r')
исправлено

2021-12-11 13:43 UTC, khodar-nastassia commented on src/homework7/task5.py
> +    years_movies = open('src/homework7/out/years.txt', 'a')
исправлено

2021-12-11 13:44 UTC, khodar-nastassia commented on src/homework7/task5.py
> +    write_Years(years_movies)
исправлено

2021-12-13 18:05 UTC, Shurke reviewed
Итоговая оценка - 9.

2021-12-13 18:05 UTC, Shurke commented on src/homework7/task2.py
> +            f.write(f'Результат вызова функции - {res}.\n')
Как маленькая придирка, ваша функция будет возвращать `None` и его же писать в файл :)

2021-12-13 18:05 UTC, Shurke commented on src/homework7/task3.py
> +        if (index != length - 1):
Тоже придирка. Скобки тут не нужны.

2021-12-13 18:05 UTC, Shurke commented on src/homework7/task5.py
> +    pattern = re.compile(r"([0-9]\.[0-9])([0-9,:?!\- a-zA-Z.�пїЅ']+)(\([0-9\/I]{4,6}\))")
+1 за использование регулярок :)
p.s. это уже не первая домашка, где они используются.

2021-12-13 18:05 UTC, Shurke commented on src/homework7/task5.py
> +lines_top250 = ''
Если это константа, то именование должно быть с большой буквы.
Я бы советовал данные переменные возвращать результат работы функции, которая у вас располагается с 55 по 72 строку (кстати говоря, а почем не оформлена как функция?). и потом уже передавать в `write_top250()`, `write_ratings()` и `write_years()` для записи в файл.

2021-12-13 18:05 UTC, closed without merging