Homework7: Ales Rovba
Shurke/pt1-43-21 pull request #50
Opened 2021-11-14 23:53 UTC by Ranok3

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-02 13:23 UTC, Shurke requested changes
Рекомендовал бы потренироваться в написании строк документации к функциям, чтобы наработать данный навык.

2021-12-02 13:23 UTC, Shurke commented on src/homework7/t7_home.py
> +    from math import sqrt
Импорт осуществляется на уровне модуля. Как, к примеру, в `src/homework7/t2_home.py`.

2021-12-02 13:23 UTC, Shurke commented on src/homework7/task1.py
> +f = [t1_home.func, getattr(t2_home, 'func'), getattr(t3_home, 'func'), getattr(t4_home, 'func'),
Для практики можете попробовать автоматизировать сбор имен функций.

2021-12-02 13:23 UTC, Shurke commented on src/homework7/task3.py
> +    global prev_item
Точно ли нужна именно глобальная переменная?
Т.к. исходя из кода, на уровне модуля переменная и именем `prev_item` не объявлена.

2021-12-02 13:23 UTC, Shurke commented on src/homework7/task3.py
> +print(get_ranges([2, 3, 8, 9]))
В вашем случае на выходе получается список вида `['2-3', '8-9']`, в то время как пример показывает строку. Вам осталось всего лишь добавить сбор строки из элементов списка.

2021-12-02 13:23 UTC, Shurke commented on src/homework7/task4.py
> +    k = n
Для чего выполнено создание переменной `k`? Если можно работать напрямую с переменной `n`.

2021-12-02 13:23 UTC, Shurke commented on src/homework7/task5.py
> +                f.write('{}: {}\n'.format(item[0], item[1][0]))
Во время выполнения основной программы, вы 3 раза выполняете функцию `films_list`. Т.е. выполняете трижды чтение из файла и обработку всех данных. Будет достаточно перед 44 строкой получить данные, а потом уже данные записывать в файлы, не проводя каждый раз вызов `films_list`.

2021-12-02 13:26 UTC, Ranok3 commented on src/homework7/t7_home.py
> +    from math import sqrt
Первые решения они такие)

2021-12-02 13:26 UTC, Ranok3 commented on src/homework7/task1.py
> +f = [t1_home.func, getattr(t2_home, 'func'), getattr(t3_home, 'func'), getattr(t4_home, 'func'),
понял как это делать, обсуждали на занятии

2021-12-02 13:27 UTC, Ranok3 commented on src/homework7/task3.py
> +    global prev_item
не нужна, но без этого при загрузке пул реквеста показывало ошибку

2021-12-02 13:31 UTC, Ranok3 commented on src/homework7/task3.py
> +print(get_ranges([2, 3, 8, 9]))
согласен, поправил

2021-12-02 13:35 UTC, Ranok3 commented on src/homework7/task4.py
> +    k = n
Согласен, поправил

2021-12-02 13:44 UTC, Ranok3 commented on src/homework7/task5.py
> +                f.write('{}: {}\n'.format(item[0], item[1][0]))
согласен, поменял

2021-12-13 18:08 UTC, Shurke commented
Итоговая оценка - 8.

2021-12-13 18:08 UTC, closed without merging