Homework7: Alexander Ustinov
Shurke/pt1-43-21 pull request #52
Opened 2021-11-21 09:05 UTC by MrGo1d

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-02 14:31 UTC, Shurke requested changes
Потренируйтесь писать строки документации для функций. Вам потом самому будет проще.

2021-12-02 14:31 UTC, Shurke commented on src/Homework_7/task1.py
> +                    print(func, ':', '\n', getattr(mod, func)(), '\n', sep='')
Может подумать над тем, чтобы организовать какой-нибудь словарь, чтобы в нем, допустим, хранилось имя функции и модуль, к которому относится она. Тогда будет достаточно через `get` получить модуль и после уже от модуля через `getattr` саму функцию.

2021-12-02 14:31 UTC, Shurke commented on src/Homework_7/task2.py
> +        fh.close()
Контекстный менеджер сам закроет файл.

2021-12-02 14:31 UTC, Shurke commented on src/Homework_7/task3.py
> +    print(*[str(i[0]) + '-' + str(i[-1]) if len(i) > 1 else str(i[-1]) for i in total], sep=',')
Подготовку данных лучше вынести за пределы `print`. И печатать уже подготовленный результат.

2021-12-02 14:31 UTC, Shurke commented on src/Homework_7/task5.py
> +        years = open('years.txt', 'w')
Для чего открывать файлы и держать их открытыми во время подготовки данных?
Более логично:
- открыть исходный файл с данными
- вычитать данные (причем можно сделать функцию-генератор, которая будет отдавать только нужное количество строк в итоге, а не выгружать весь файл в память)
- обработать данные
- записать данные в нужные файлы

2021-12-02 14:31 UTC, Shurke commented on src/Homework_7/task5.py
> +def pars(file):
Хочу предложить вам поработать над декомпозицией вашей функции. Можно выделить следующие части: чтение данных, обработка и запись в файл.

2021-12-05 13:40 UTC, MrGo1d commented on src/Homework_7/task1.py
> +                    print(func, ':', '\n', getattr(mod, func)(), '\n', sep='')
Откорректировал: все функции теперь хранятся в словаре, где ключ - имя функции, значение - имя модуля.

2021-12-05 13:40 UTC, MrGo1d commented on src/Homework_7/task2.py
> +        fh.close()
Удалил эту строку.

2021-12-05 13:40 UTC, MrGo1d commented on src/Homework_7/task3.py
> +    print(*[str(i[0]) + '-' + str(i[-1]) if len(i) > 1 else str(i[-1]) for i in total], sep=',')
Откорректировал.

2021-12-05 13:41 UTC, MrGo1d commented on src/Homework_7/task5.py
> +def pars(file):
Готово!

2021-12-05 13:43 UTC, MrGo1d commented on src/Homework_7/task5.py
> +        years = open('years.txt', 'w')
Разбил функцию на части:
-генератор данных
-обоаботка данных
-запись данных в файл

2021-12-13 18:43 UTC, Shurke reviewed
Итоговая оценка - 9.

2021-12-13 18:43 UTC, Shurke commented on src/Homework_7/task1.py
> +    if len(args) == 0:
Придирка.)
`if args:` - более питонистичный вариант

2021-12-13 18:43 UTC, Shurke commented on src/Homework_7/task5.py
> +draw_gist(dict_of_year)
Придирка. 
Вызовы этих функций можно было поместить в функцию, к примеру `main()`.

2021-12-13 18:43 UTC, closed without merging