Homework7: Elena Okun
Shurke/pt1-43-21 pull request #53
Opened 2021-11-21 18:42 UTC by ElenaOkun

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-02 14:54 UTC, Shurke requested changes
Рекомендую потренироваться в написании строк документации к функции. Вам потом будет полезен данный навык.

2021-12-02 14:54 UTC, Shurke commented on src/homework7/task1.py
> +        f = getattr(tasks_homework2, func_name, None)
`getattr` по умолчанию возвращает `None`. Нет необходимости задавать его руками.

2021-12-02 14:54 UTC, Shurke commented on src/homework7/task1.py
> +    if module is None:
Можно сделать словарь, который хранит пары `имя_функции: модуль_откуда_функция`. Тогда проверка сведется к вызову метода `get` и получения модуля. Если модуль есть, то через `getattr` получить функции и потом выполнить ее.

2021-12-02 14:54 UTC, Shurke commented on src/homework7/task2.py
> +        f.close()
Работу с файлом лучше поместить в контекстный менеджер.

2021-12-02 14:54 UTC, Shurke commented on src/homework7/task5.py
> +def create_file_top250(list_of_rate):
Для данной задачи замечание о контекстных менеджерах актуально.

2021-12-02 14:54 UTC, Shurke commented on src/homework7/task8.py
> +        return None
Можно рассмотреть следующий подход
```py
functions = {
    "AND":  logic_and,
    "OR":  logic_or,
}
```
(все функции не добавляю, думаю идея понятна)
Далее просто делаете `functions.get(function_name)` и работаете с полученной функцией. Или, если нет такой функции, то выводите нужное сообщение.

2021-12-04 20:18 UTC, ElenaOkun commented on src/homework7/task1.py
> +        f = getattr(tasks_homework2, func_name, None)
Убрала None

2021-12-04 20:19 UTC, ElenaOkun commented on src/homework7/task1.py
> +    if module is None:
Переделала со словарем

2021-12-04 20:19 UTC, ElenaOkun commented on src/homework7/task5.py
> +def create_file_top250(list_of_rate):
Исправила

2021-12-04 20:19 UTC, ElenaOkun commented on src/homework7/task2.py
> +        f.close()
Исправила

2021-12-04 20:20 UTC, ElenaOkun commented on src/homework7/task8.py
> +        return None
Заменила на словарь

2021-12-13 19:00 UTC, Shurke reviewed
Итоговая отметка - 9.5

2021-12-13 19:01 UTC, closed without merging