Homework7: Andrei Barysevich
Shurke/pt1-43-21 pull request #55
Opened 2021-11-22 22:41 UTC by Crankymonk

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-30 18:13 UTC, Shurke commented on src/homework7/task5.py
> +        file.close()
Для чего тогда тут используется контекстный менеджер, если вы руками закрываете файл?

2021-11-30 18:13 UTC, Shurke commented on src/homework7/task1.py
> +            func = getattr(func_collection, function)
Подсказываю.
Поменяйте 10 и 11 строку местами.)

2021-12-02 15:45 UTC, Shurke requested changes

2021-12-02 15:45 UTC, Shurke commented on src/homework7/task1.py
> +    if len(args) == 0:
Кстати говоря, данную проверку можно сделать более питонообразной. 
```py
if not len(args):
```

2021-12-02 15:45 UTC, Shurke commented on src/homework7/task2.py
> +        fh.close()
Контекстный менеджер сам закроет файл.

2021-12-02 15:45 UTC, Shurke commented on src/homework7/task3.py
> +def get_ranges(sorted_list=list) -> list:
Вашу функцию можно декомпозировать. 
В отдельную функцию вынести строки с 19 по 29 и во вторую - строки с 31 по 40.

2021-12-16 17:36 UTC, Crankymonk commented on src/homework7/task2.py
> +        fh.close()
Совершенно верно, ведь контекстный менеджер содержит в себе магический метод `__exit__` , который выполнится после выхода из блока `with` ))больше не повторится)

2021-12-16 19:00 UTC, Crankymonk commented on src/homework7/task1.py
> +            func = getattr(func_collection, function)
не помогло и не удивительно) 
все гораздо проще: я искал `function.__doc__` при том, что добытые при помощи `getattr` атрибуты поместил в `func`

2021-12-16 19:01 UTC, Crankymonk commented on src/homework7/task1.py
> +            func = getattr(func_collection, function)
точнее - поменять нужно было, но это не спасало положение и я долго и упорно не понимал в чем дело)

2021-12-17 16:18 UTC, Shurke reviewed
Итоговая оценка - 6.

2021-12-17 16:18 UTC, Shurke commented on src/homework7/task5.py
> +        fh.close()
А почему здесь не сложилось с контекстными менеджерами?)

2021-12-17 16:18 UTC, Shurke commented on src/homework7/task4.py
> +    return print(f'Результат построения двоичной пирамиды для данных чисел: {binary_summ}')
При таком подходе, функция `bin_func` будет возвращать `None`, т.к. функция `print` возвращает `None`.

2021-12-17 16:18 UTC, Shurke commented on src/homework7/task3.py
> +    return print(f'Результат свернутого списка: {collapsed_string}')
При таком подходе, функция `get_rangie` будет возвращать `None`, т.к. функция `print` возвращает `None`.

2021-12-17 16:18 UTC, closed without merging

2022-01-02 09:39 UTC, Crankymonk commented on src/homework7/task5.py
> +        fh.close()
в рамках дз пробую разными вариантами