Homework7: Kirill Filitchonok
Shurke/pt1-43-21 pull request #58
Opened 2021-11-23 14:24 UTC by KirPython

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-02 16:13 UTC, Shurke requested changes
Для функций стоит писать строки документации.

2021-12-02 16:13 UTC, Shurke commented on src/homework7/task1.py
> +    }
Такой подход приводит к тому, что любое изменение в модуле, откуда импортирована функция, вызывает необходимость внесения исправлений руками.

2021-12-02 16:13 UTC, Shurke commented on src/homework7/task2.py
> +            file.close()
Работу с файлами следует осуществлять с помощью контекстного менеджера.

2021-12-02 16:13 UTC, Shurke commented on src/homework7/task5.py
> +def movies():
Данную функцию можно декомпозировать. Легко можно выделить три части: чтение из файла, обработка данных и запись в файлы. На лекции обсуждалось, что функция должна делать какое-то одно простое действие, а не покрывать всю необходимую работу за раз.

2021-12-05 16:45 UTC, KirPython commented on src/homework7/task5.py
> +def movies():
Исправлено.

2021-12-13 19:43 UTC, Shurke reviewed
Итоговая отметка - 7.5.
0.5 снял за закрытие файла в теле контекстного менеджера.

2021-12-13 19:43 UTC, Shurke commented on src/homework7/task2.py
> +                f.close()
Контекстный менеджер сам закрывает файл.

2021-12-13 19:43 UTC, Shurke commented on src/homework7/task2.py
> +            f.close()
См. выше.

2021-12-13 19:43 UTC, Shurke commented on src/homework7/hw5.py
> +        print('hw5 task3')
Строго говоря, то это статические методы.

2021-12-13 19:43 UTC, closed without merging