Homework15: Nastassia Khodar
Shurke/pt1-43-21 pull request #62
Opened 2021-12-12 14:07 UTC by khodar-nastassia

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-26 19:26 UTC, Shurke requested changes
Стоит расширить количество тестов.

2021-12-26 19:26 UTC, Shurke commented on src/homework15/task1.py
> +class Transformer(Heroes, Weapon):
Не очень удачная модель множественного наследования.
Вы пытаетесь наследовать в классе персонажа свойства и героя, и оружия. Что чисто логически выглядит для меня немного странно. Это как словно бы Эльф наследовал черты своей расы, но в тоже время и черты своего лука.
Думаю, что более удачным вариантом будет не наследовать класс `Weapon`, а создавать экземпляр оружия в классе героя.
Например
```py
class Transformer(Heroes):
    def __init__(self, name, race, right_hand, left_hand):
        Heroes.__init__(self, name, race)
        self.right_hand = Weapon()
        self.left_hand = Weapon()
```
Перечитайте еще раз теорию про агрегацию и композицию в ООП, думаю должно помочь.

2021-12-26 19:26 UTC, Shurke commented on src/homework15/task2.py
> +@decorator(n=int(input()))
Мы уже не раз обсуждали, что не самый удачный подход, когда мы и получаем данные, и конвертируем их и передаем куда-то. И все в одном месте.
Если вы хотите динамически создавать функцию, то получайте параметр с клавиатуры, а потом вызывайте декоратор без синтаксического сахара и передайте туда полученное с клавиатуры значение.

2022-01-04 14:43 UTC, khodar-nastassia commented on src/homework15/task1.py
> +class Transformer(Heroes, Weapon):
Попыталась.

2022-01-04 14:43 UTC, khodar-nastassia commented on src/homework15/task2.py
> +@decorator(n=int(input()))
Исправила

2022-01-09 17:51 UTC, Shurke commented
Итоговая оценка - 8.

2022-01-09 17:51 UTC, closed without merging