Homework15: Alex Ustinov
Shurke/pt1-43-21 pull request #65
Opened 2021-12-20 19:09 UTC by MrGo1d

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-26 20:04 UTC, Shurke requested changes

2021-12-26 20:04 UTC, Shurke commented on src/Homework_15/tests_task2.py
> +import unittest
> C0411: standard import "import unittest" should be placed before "import task3" (wrong-import-order)

Ваши импорты должны идти так
```py
import unittest

from ddt import data
from ddt import ddt
from ddt import unpack

import task2
```

2021-12-26 20:04 UTC, Shurke commented on src/Homework_15/tests_task2.py
> +import task2
А пробовали ли импортировать?
```py
from Homework_15 import task2
```

2021-12-27 04:24 UTC, MrGo1d commented on src/Homework_15/tests_task2.py
> +import unittest
Вообще все сломалось((

2021-12-27 04:24 UTC, MrGo1d commented on src/Homework_15/tests_task2.py
> +import task2
Попробовал - подсвечиает красным. Запушил.

2021-12-27 17:31 UTC, Shurke requested changes
У тестов должны быть осмысленные имена, а не `test_1`.)

2021-12-27 17:31 UTC, Shurke commented on src/Homework_15/task2.py
> +# print(some_func(1))
Вновь просочился закоменченный код.)

2021-12-27 17:31 UTC, Shurke commented on src/Homework_15/task1.py
> +               f"Level: {self.level}"
Тут можно использовать магический метод `__str__`.

2021-12-27 17:31 UTC, Shurke commented on src/Homework_15/task1.py
> +    EXPERIENCE = 0
Я думаю, что опыт должен быть атрибутом экземпляра, а не класса.
Чтобы каждый новый персонаж появлялся с 0 опытом, а не с каким-то значением.
Поправьте меня, если я ошибаюсь.

2021-12-27 17:31 UTC, Shurke commented on src/Homework_15/task2.py
> +        num_of_call = int(input('Enter nums of decorator calls: '))
Параметр количества вызовов должен передаваться в декоратор, а не получаться в нем от пользовательского ввода.

2021-12-27 17:31 UTC, Shurke commented on src/Homework_15/task4.py
> +# @njit()
Вновь просочился закоменченный код.)

2021-12-31 07:46 UTC, MrGo1d commented on src/Homework_15/task2.py
> +# print(some_func(1))
Убрал.

2021-12-31 07:46 UTC, MrGo1d commented on src/Homework_15/task1.py
> +               f"Level: {self.level}"
Отредактировал.

2021-12-31 07:47 UTC, MrGo1d commented on src/Homework_15/task1.py
> +    EXPERIENCE = 0
Все верно вы написали. Переделал.

2021-12-31 07:48 UTC, MrGo1d commented on src/Homework_15/task2.py
> +        num_of_call = int(input('Enter nums of decorator calls: '))
Откорректировал.

2021-12-31 07:54 UTC, MrGo1d commented on src/Homework_15/task4.py
> +# @njit()
Искал способы ускорить код для решения задачи Эйлера. Набрел на модуль numba. Git тесты не пропускали этот импорт. Но, т.к. все остальные тесты тоже не проходят - раскоментил код)

2022-01-03 15:55 UTC, Shurke reviewed
Итоговая оценка - 8.

2022-01-03 15:55 UTC, closed without merging