Hometask15: Raman Rylko
Shurke/pt1-43-21 pull request #67
Opened 2021-12-21 12:16 UTC by rylkorom

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-27 17:46 UTC, Shurke requested changes

2021-12-27 17:46 UTC, Shurke commented on src/hometask15/task2.py
> +    def __init__(self, room_num: int = None):
Метод `__init__` лучше помещать выше других методов. Чтобы сразу после объявления класса шел `__init__`, а потом уже все остальное.

2021-12-27 17:46 UTC, Shurke commented on src/hometask15/test_task3.py
> +from task3 import LengthError
Когда идет такое количество импортов с одного модуля, то проще сделать импорт всего модуля и потом обращаться к нужным объектам `task3.ArgumentsError` и т.д. Тоже самое относится к `ddt`.
Это замечание относится и к другим тестам.

2022-01-03 15:58 UTC, Shurke requested changes
Замечания не устранены.

2022-01-03 16:06 UTC, rylkorom commented
> Замечания не устранены.
Александр, подскажите пожалуйста, в каком конкретно задании не устранены замечания?
Так как во втором задании я поменял местами функции и __init__ стала первой, а также я заменил импорты во всех тестах + добавил тесты на задание с классами( моделью из реальной жизни). Заранее спасибо.

2022-01-09 18:07 UTC, Shurke commented on src/hometask15/test_task2.py
> +    #     print(client.name)
Если код закомментирован, то его не должно быть в итоговом решении.

2022-01-09 18:07 UTC, Shurke commented on src/hometask15/test_task2.py
> +        for room in task2.Reception.rooms:
У вас сейчас тесты зависят от кода, который тестируется (используется атрибут класса из модуля `Reception`).
В идеале, тест должен выглядеть так:
1. Создали нужные объекты (моки и т.д.)
2. В тестируемую функцию, как в черный ящик, передали значения и получили какой-то результат.
3. Результат работы тестируемой функции сравнили с ожидаемым.

Наличие циклов, условных конструкций в тестах стоит избегать и не применять без крайней необходимости.

2022-01-09 18:08 UTC, Shurke commented
> > Замечания не устранены.
> > Александр, подскажите пожалуйста, в каком конкретно задании не устранены замечания?
> > Так как во втором задании я поменял местами методы и **init** стал первым, а также я заменил импорты во всех тестах + добавил тесты на задание с классами( моделью из реальной жизни). Заранее спасибо.

Скорей всего посмотрел не финальный коммит. Извиняюсь.
Итоговая оценка - 7.5.

2022-01-09 18:08 UTC, closed without merging