Homework15: Kirill Filitchonok
Shurke/pt1-43-21 pull request #68
Opened 2021-12-21 15:05 UTC by KirPython

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-27 17:36 UTC, Shurke requested changes

2021-12-27 17:36 UTC, Shurke commented on src/homework15/task1.py
> +    def get_school_info(self) -> dict:
У вас функция делает сразу два действия: и выводит на экран, и возвращает словарь с данными. Более правильно будет разделить эти два действия по отдельным функциям.

2021-12-27 17:36 UTC, Shurke commented on src/homework15/task2.py
> +Парсинг фрагмента текста сайта с замером среднего времени выполнения этой операции.
+1 балл за усложнение задачи.)

2021-12-27 17:36 UTC, Shurke commented on src/homework15/test_task1.py
> +        self.assertIsNot(type(school_address), int)
Тут достаточно только одной проверки.
Логика такая, если `school_address` - это строка, то других типов данных там уже нет и не нужно проверять. 
Это замечание касается и тестов ниже в этом модуле.

2021-12-28 14:44 UTC, KirPython commented on src/homework15/task1.py
> +    def get_school_info(self) -> dict:
Исправлено

2022-01-03 15:59 UTC, Shurke reviewed
Итоговая оценка - 9.

2022-01-03 15:59 UTC, closed without merging