Homework2: Alexander Ustinov
Shurke/pt1-43-21 pull request #7
Opened 2021-10-25 21:42 UTC by MrGo1d

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-10-29 12:24 UTC, Shurke requested changes
Общие замечания:
1. Имена переменных. Стоит давать осознанные и осмысленные имена, чтобы они несли смысл.
2. На будущее, условия задач оформлять как строки документации модуля.

2021-10-29 12:24 UTC, Shurke commented on src/Homework_1/task2.py
> +        word = i.strip(string.punctuation)
В 3х строках повторяется одно и тоже действие, с удалением пунктуации.
Стоит пересмотреть решение, чтобы не делать одно и тоже действия с одним и тем же элементом.

2021-10-29 12:24 UTC, Shurke commented on src/Homework_1/task2.py
> +"""2. Найти самое длинное слово в введенном предложении. Учтите что в предложении
Сначала помещается строка документации модуля, а после уже организуются все импорты.

2021-10-29 12:24 UTC, Shurke commented on src/Homework_1/task4.py
> +    if i.lower() in string.ascii_lowercase:
Стоит пересмотреть подход к решению, чтобы сделать его более явным и использовать этого методы `islower()` и `isupper()` для проверки заглавная буква или нет.

2021-10-29 12:24 UTC, Shurke commented on src/Homework_1/task6.py
> +for i in range(count + 1):
Действительно ли нам нужно два цикла в данном случае?

2021-10-29 12:24 UTC, Shurke commented on src/Homework_1/task8.5.py
> +    return True if sum((int(i) ** len(str(value))) for i in str(value)) == value else False
Стоит избегать таких решений, т.к. в них очень сложно разобраться. При написании кода мы должны помнить о том, что код мы читаем чаще, чем пишем. И должны поддерживать читаемость кода.

2021-10-30 08:39 UTC, MrGo1d commented on src/Homework_1/task4.py
> +    if i.lower() in string.ascii_lowercase:
Александр, а если обойти **islower()** **isupper()** провркой вхождения в **string.ascii_lowercase** и **string.ascii_uppercase** соответственно? Т.к. нам в любом случае нужно убедится, что буква английская:

for i in text:
    if i in string.ascii_uppercase:
        cap_letter += 1
    elif i in string.ascii_lowercase:
        low_letter += 1

Получается, можно обойтись без дополнительной проверки на регистр.
Или обязательно через методы **islower()** и **isupper()**?

2021-11-01 19:53 UTC, MrGo1d commented on src/Homework_1/task2.py
> +        word = i.strip(string.punctuation)
Откорректировал: ввел локальную переменную 'value'

2021-11-01 19:54 UTC, MrGo1d commented on src/Homework_1/task2.py
> +"""2. Найти самое длинное слово в введенном предложении. Учтите что в предложении
Откорректировал.

2021-11-01 19:55 UTC, MrGo1d commented on src/Homework_1/task6.py
> +for i in range(count + 1):
Откорректировал: вложился в один цикл.

2021-11-01 19:56 UTC, MrGo1d commented on src/Homework_1/task8.5.py
> +    return True if sum((int(i) ** len(str(value))) for i in str(value)) == value else False
Расписал решение без испоьзования однострочных конструкций.

2021-11-06 10:54 UTC, Shurke reviewed
Итоговая оценка - 9.

2021-11-07 13:58 UTC, closed without merging