Homework15
Shurke/pt1-43-21 pull request #71
Opened 2021-12-27 16:15 UTC by AndreiKadushko

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-27 17:41 UTC, Shurke requested changes

2021-12-27 17:41 UTC, Shurke commented on src/Homework15/task1.py
> +# import time
Если закоментировано, значит и не нужно.

2021-12-27 17:41 UTC, Shurke commented on src/Homework15/task1.py
> +        return print(out_str)
Функция `print` возвращает `None`. Функция `dimensions_tree` точно также будет возвращать `None`.

2021-12-27 17:41 UTC, Shurke commented on src/Homework15/task1.py
> +        return print(out_type)
См. замечание выше про возврат `print`.

2021-12-29 18:04 UTC, AndreiKadushko commented on src/Homework15/task1.py
> +# import time
Не увидел при при просмотре перед отправкой

2021-12-29 18:07 UTC, AndreiKadushko commented on src/Homework15/task1.py
> +        return print(out_str)
Хотел протестировать результат функции. Там должна быть out_str, но переключился на другие тесты

2021-12-29 18:07 UTC, AndreiKadushko commented on src/Homework15/task1.py
> +        return print(out_type)
То же самое.

2022-01-03 16:01 UTC, Shurke reviewed
Итоговая оценка - 8.5.

2022-01-03 16:02 UTC, closed without merging