Homework15: Andrei Barysevich
Shurke/pt1-43-21 pull request #72
Opened 2021-12-28 12:35 UTC by Crankymonk

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-12-28 15:00 UTC, Crankymonk commented
Flake8 не проходит только потому, что не определяет, что импортировалось через *

2022-01-03 16:18 UTC, Shurke requested changes

2022-01-03 16:18 UTC, Shurke commented on src/homework15/task1.py
> +        pass
И для чего здесь и ниже нужен `pass`?

2022-01-03 16:18 UTC, Shurke commented on src/homework15/task1.py
> +        print(f'Сумма бонусных баллов - {self.loyalty}')
Для такого вывода информации можно применить магический метод `__str__`.

2022-01-03 16:18 UTC, Shurke commented on src/homework15/task3.py
> +pair_counter_func()
Как только будет импортирован модуль, код выполнится.
Чего, по идее, быть не должно.

2022-01-03 16:18 UTC, Shurke commented on src/homework15/task4.py
> +sum_func([7, 15, 100])
См. замечание про импорт модуля.

2022-01-03 19:39 UTC, Crankymonk commented on src/homework15/task1.py
> +        pass
Выставлял pass, когда продумывал методы, не заполняя

2022-01-09 18:20 UTC, Shurke requested changes

2022-01-09 18:20 UTC, Shurke commented on src/homework15/task1.py
> +        pass
Вы точно уверены, что хотите тут переопределить метод `__init__` из родительского класса `Item`?

2022-01-09 18:20 UTC, Shurke commented on src/homework15/task1.py
> +    def __init__(self, ):
Полагаю, что имели ввиду `def __init__(self):`

2022-01-09 18:20 UTC, Shurke commented on src/homework15/task1.py
> +class Customer():
Лишние скобки.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/task1.py
> +        return name + current_account + loyalty_summ
Итоговую строку лучше формировать через форматирование или f-строку.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/task1.py
> +    def item_info(self):
Аналогично классу `Customer`, можно использовать магический метод `__str__` для отображения информации о товаре.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/task1.py
> +class Payment():
Лишние скобки.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/task1.py
> +# cart_1.remove_from_cart(pizza_1)
Если закомментировано, значит в коде не нужно.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/task2.py
> +                fun()
Декоратор нигде не возвращает результат выполнения функции.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/test_task3.py
> +    @ unpack
Опечатка.
Правильный вариант - `@unpack`.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/test_task3.py
> +    @ unpack
Опечатка.
Правильный вариант - `@unpack`.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/test_task3.py
> +    @ unpack
Опечатка.
Правильный вариант - `@unpack`.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/test_task4.py
> +        self.assertEqual(great_comm_divisor(8, -9), 1)
Здесь можно применить библиотеку `ddt`, если говорим о `unittest`.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/test_task4.py
> +        self.assertEqual(max_m(7), 1)
Здесь можно применить библиотеку `ddt`.

2022-01-09 18:20 UTC, Shurke commented on src/homework15/test_task4.py
> +import unittest
Очень странно видеть две библиотеки тестирования в одном модуле.
Пожалуйста, определитесь и выберите одну.

2022-01-13 19:09 UTC, Crankymonk commented on src/homework15/test_task4.py
> +import unittest
Вообще хотелось разные варианты попробовать, unittest, pytest и ddt. Мы же учимся)

2022-01-13 22:48 UTC, Crankymonk commented
Нужна помощь. Я не понимаю в чем дело 
"./src/homework15/task1.py:38:15: E999 SyntaxError: invalid syntax"

2022-01-13 22:51 UTC, Crankymonk commented
> Нужна помощь. Я не понимаю в чем дело "./src/homework15/task1.py:38:15: E999 SyntaxError: invalid syntax"

Flake8 настроен на python 3.9, а я заюзал pattern matching из 3.10. Ясно-понятно, разобрался)

2022-01-26 18:18 UTC, Shurke reviewed
Итоговая отметка - 7.

2022-01-26 18:19 UTC, closed without merging