Homework15
Shurke/pt1-43-21 pull request #73
Opened 2021-12-28 13:09 UTC by mmfszhl

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.
![homework15_flake](https://user-images.githubusercontent.com/92994819/147569428-d032ab7a-7bb3-4a72-92e1-874b3b4f0a52.png)

К сожалению не успел в task1 докрутить, чтобы игра шла до счета 3 в чью-либо пользу.

2022-01-03 16:13 UTC, Shurke requested changes
Не хватает тестов для игры из `src/homework15/task1.py`.

2022-01-03 16:13 UTC, Shurke commented on src/homework15/task2.py
> +    num_calls = int(input("Please enter call amount:"))
> n раз - параметр декоратора

А не через ввод пользователем с клавиатуры.

2022-01-03 16:13 UTC, Shurke commented on src/homework15/task1.py
> +            if choice not in range(1, 3):
3-я опция является недостижимой.
![Screenshot 2022-01-03 at 19 11 44](https://user-images.githubusercontent.com/44495358/147953347-118fc010-fece-4779-a597-f8cd9ee20ac2.png)

2022-01-03 16:13 UTC, Shurke commented on src/homework15/task1.py
> +    # while gamer_wins < 3 or npc_wins < 3:
Это закомментированная строка кода или комментарий к коду?

2022-01-03 16:13 UTC, Shurke commented on src/homework15/task3.py
> +class TestTask(unittest.TestCase):
Тесты лучше вынести в отдельный файл.

2022-01-12 19:01 UTC, mmfszhl commented on src/homework15/task1.py
> +    # while gamer_wins < 3 or npc_wins < 3:
Изначально хотел сделать игру до 3х побед. Доработал, теперь работает.

2022-01-12 20:39 UTC, mmfszhl commented
> 
Added task1_test + flake8 passed screenshot
![hw15_fixes_flake8](https://user-images.githubusercontent.com/92994819/149217967-be789407-9f9c-4c48-b0a4-34b981fbad7b.png)

2022-01-26 18:50 UTC, Shurke reviewed
Итоговая оценка - 7.

2022-01-26 18:51 UTC, closed without merging