Homework5: Yana Kaziuchyts
Shurke/pt1-43-21 pull request #74
Opened 2022-01-25 21:23 UTC by Vinichek

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-01-26 19:24 UTC, Shurke requested changes

2022-01-26 19:24 UTC, Shurke commented on src/homework5/task4.py
> +        all_lst = fh.readlines()
Не могу сказать, что данный подход будет удачным, т.к. в память выгружается весь файл. 
Более разумным было бы читать строка за строкой до получения нужного количества данных.

2022-01-26 19:24 UTC, Shurke commented on src/homework5/task3.py
> +def get_ranges(lst):
Не самое удачное именование переменных в данном решении. Сложно понять, что хранится в каждой из них.

2022-01-26 19:24 UTC, Shurke commented on src/homework5/task5.py
> +    return
Для чего здесь добавлена инструкция `return`?

2022-01-26 19:24 UTC, Shurke commented on src/homework5/task6.py
> +    return print(div)
Функция будет возвращать `None`, т.к. `print` возвращает `None`.

2022-01-27 18:02 UTC, Vinichek commented on src/homework5/task5.py
> +    return
Исправлено

2022-01-27 18:02 UTC, Vinichek commented on src/homework5/task6.py
> +    return print(div)
Исправлено

2022-02-06 18:31 UTC, Shurke commented
Итоговая оценка - 7.5.

2022-02-06 18:31 UTC, closed without merging