Homework2: Elena Okun
Shurke/pt1-43-21 pull request #8
Opened 2021-10-25 22:28 UTC by ElenaOkun

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-10-29 12:14 UTC, Shurke requested changes
Общие замечания:

1. Имена переменных. Стоит давать осознанные и осмысленные имена, чтобы они несли смысл.
2. На будущее, условия задач оформлять как строки документации модуля.
3. Также, на будущее, стоит добавлять строки документации в функции, раз вы решили использовать их для оформления вашего решения.

2021-10-29 12:14 UTC, Shurke commented on src/homework2/task2.py
> +    import string
Импорт осуществляется в начале модуля, за строкой документации, а не в теле функции.

2021-10-29 12:14 UTC, Shurke commented on src/homework2/task2.py
> +        print(list_of_words[0])
Проверки такого рода можно и нужно осуществлять в начале. Т.е. сразу можно проверить исходную строку, пустая она или нет. Далее проверить уже наличие слов в ней. Если словно одно, то сразу вывести его.
А только потом уже осуществлять остальные действия.

2021-10-29 12:14 UTC, Shurke commented on src/homework2/task3.py
> +        result_string = result_string + i
Или `result_string += i`

2021-10-29 12:14 UTC, Shurke commented on src/homework2/task7.py
> +        return
Можно следующим образом переписать
```py
try:
    a = float(a)
    b = float(b)
    c = float(c)
except ValueError:
    print("Это не число!")
    return
```
в таком случае, количество строк уменьшится. Т.к. функциональность повторяется.

2021-11-06 11:10 UTC, Shurke requested changes
Не устранены замечания предыдущего раунда ревью.

2021-11-06 11:10 UTC, Shurke commented on src/homework2/Task1.py
> +        return
Смотрите замечание, которое оставлял к задаче 7.

2021-11-09 13:08 UTC, ElenaOkun commented on src/homework2/task2.py
> +    import string
Исправила

2021-11-09 13:08 UTC, ElenaOkun commented on src/homework2/task3.py
> +        result_string = result_string + i
Принято

2021-11-09 13:08 UTC, ElenaOkun commented on src/homework2/task7.py
> +        return
Исправила

2021-11-09 13:10 UTC, ElenaOkun commented on src/homework2/task2.py
> +        print(list_of_words[0])
Исправила сообщение

2021-11-11 19:53 UTC, Shurke commented
Итоговая оценка - 7.5.

2021-11-11 19:53 UTC, closed without merging